### ISSUE TITLE
question/bug about formatting

### ISSUE THREAD

**Issue by calvario-31** [RankWeis/uppercut#36] opened 2024-11-02 05:58 UTC
Hi, wanted to say thanks for this plugin

Possible bug:
However I found this, wonder if it is working as expected?

![image](https://github.com/user-attachments/assets/0ba48b00-2558-47b5-808d-f635ddf32d1d)

Im trying to format this using IntelliJ however is not working:
- tried with format on save
- right click format code

My expected result would be this:
![image](https://github.com/user-attachments/assets/e0ae6199-3f01-418c-9634-42865fec278d)

Bug:
When I run clicking on play, the karate.log is not populated. Only is being populated if i run using the runner

![image](https://github.com/user-attachments/assets/7e085b56-9437-4de3-ab75-2717b3712b9c)

**Comment by calvario-31** [comment] 2024-11-02 16:30
I made some digging about the no logs issue.
![image](https://github.com/user-attachments/assets/2290c5f6-25db-450e-884f-82dc86438a01)
It says logback-test.xml is duplicated 

- one that comes from your plugin
- the one comes with karate template

![image](https://github.com/user-attachments/assets/06e1ac3f-7384-4797-9adf-3f1e2001d321)

If I delete the logback-test.xml that comes with the karate template i can see the logs on the terminal but no .log file is being generated

**Comment by RankWeis** [comment] 2024-11-02 17:28
I don't think I ever got around to the autoformat portion of the plugin, that's probably my next major feature! I will use this as impetus to get to it.

As for the karate.log problem, thanks for the investigation. I will look into this but because I don't populate the karate.log but instead rely on the karate plugin to do it, it may be a bit out of my hands. But still, will try my best to get something working. Thanks!

**Comment by calvario-31** [comment] 2024-11-03 00:44
I think the karate logs are populated by logback-test.xml the karate plugin only helps for formatting and run (if you pay)

**Comment by calvario-31** [comment] 2024-11-03 00:53
Please let me know if I can help in something. I believe the logs is pretty important for debugging

**Comment by RankWeis** [comment] 2024-11-04 13:00
I have a release sent to intellij that should address this problem. They usually approve within 12 hours but could take up to 2 days.

**Comment by calvario-31** [comment] 2024-11-04 15:01
tyvm, im looking forward to it. Please let me know if i can help in something

**Comment by RankWeis** [comment] 2024-11-04 15:35
Actually they ended up approving it very quickly. Please take a look at your convenience and see if it does what you expect it to do and I will close this ticket, thanks!

**Comment by calvario-31** [comment] 2024-11-04 15:38
yes is working now, thank you very much. This ticket can be closed
Hope the autoformat can be implemented on the future

Thanks again for your effort and for this plugin. Please let me know if you need some kind of help

**Comment by RankWeis** [comment] 2024-11-04 23:25
I'm reopening this because there's really two issues and only one was resolved. The other may be a bit bigger, but if it's exactly the issue you said, I believe I have a fix for it.

What should work:
*     Then    match    responseStatus     !=   200 =>  * Then match responseStatus    !=   200

Note that after 'match' I don't really parse the rest of the string. So it becomes tricky to format that. But before and after 'match' I can fix this pretty easily, and that's technically the issue you pointed out. So it's better than nothing. 

If your offer still stands, can I have you be my guinea pig for this and ensure it works as expected? I'm noticing some issues on my side that are hard to figure out but I don't think they're regressions, just weirdness in the formatting that has been there for a while.

Unzip this and then install it in intelliJ from the plugins settings page - 
![image](https://github.com/user-attachments/assets/2a031100-b5b6-410d-a020-f8139ad8f81f)

[uppercut-1.1.5.jar.zip](https://github.com/user-attachments/files/17624889/uppercut-1.1.5.jar.zip)

Then please report any findings here, I can't promise I can fix all of them but if this is a net positive to the workflow I'm happy to publish it. Thanks!

**Comment by calvario-31** [comment] 2024-11-04 23:27
sure will do in like 30min or 1h and will report

**Comment by calvario-31** [comment] 2024-11-05 00:07
my findings:

- Before and after the keyword on orange are formatting (path, method, def). So your fix is working

Suggestions/Things can be improved
- Before and after the keyword on white are not formatting (path, method, def)
- The asterisk/wildcard symbol (*) seems kinda bugged with formatting sometimes it formats sometimes i doesn't
- Parse the symbols as intellij does with java (only one space between the symbols)
`Then    match    responseStatus     !=   200 =>  * Then match responseStatus != 200`

I think is a good starting point, let me know if you have more jars to test

I would like to refer me as a tester instead of a guinea pig hehe

**Comment by RankWeis** [comment] 2024-11-05 00:23
Of course, my apologies, thank you so much for your feedback. I'll see what I can incorporate!

**Comment by RankWeis** [comment] 2024-11-05 06:16
I think this build should be a lot better with all these issues. If you could provide me an example of when  the asterisks are bugged still I'm sure I can figure that out. This is kind of a big change splitting it into word-based tokens so I'm going to test this for a week or so before sending it out to the public.
[uppercut-1.1.5.jar.zip](https://github.com/user-attachments/files/17627801/uppercut-1.1.5.jar.zip)
as well.

**Comment by calvario-31** [comment] 2024-11-05 14:42
Sure, will review in 30min aprox

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by calvario-31** [comment] 2024-11-05 15:24
hello

so far is working great, but still found this asterisk bug
![image](https://github.com/user-attachments/assets/d9b5b40a-2799-426a-8c33-79cafcc2afae)
![image](https://github.com/user-attachments/assets/66de3187-ca99-449d-91b7-3389c530f6a7)

Seems it happens when asterisk is the first step on a scenario
im using the karate template so is easier to replicate for you

**Comment by RankWeis** [comment] 2024-11-05 18:39
Thanks a lot! This helped and I think I've fixed it. All my files look good anyway. I'm going to still test and make changes for a few more days but if you want a sneak peak -
[uppercut-1.1.5.jar.zip](https://github.com/user-attachments/files/17637024/uppercut-1.1.5.jar.zip)

**Comment by calvario-31** [comment] 2024-11-05 18:51
thanks man, it works perfect

I have another query/bug regarding some reserved keywords should I open a new ticket for this?

**Closed** 2024-11-06 02:53 UTC
